-- Demo Data for Travel Booking System (H2 Database)
-- Run this in H2 Console after your application starts

-- IMPORTANT NOTES:
-- 1. Roles and Payment statuses are auto-created by RoleSeeder and PaymentSeeder
-- 2. Admin user (phone: 0123456789, password: 123456) is auto-created by RoleSeeder
-- 3. Payment status IDs: 1=PAID, 2=UNPAID, 3=VERIFYING, 4=PAYMENT_FAILED
-- 4. Role IDs: Generated by RoleSeeder (check roles table for ADMIN and USER codes)

-- 1. Insert Sample Users
-- Password for all users: "123456" (BCrypt hashed)
INSERT INTO users (phone, password, full_name, email, birthday, status, role_id) VALUES
('0987654321', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'Nguyen Van A', 'nguyenvana@example.com', '1995-05-15', true, 2),
('0912345678', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'Tran Thi B', 'tranthib@example.com', '1992-08-20', true, 2),
('0901234567', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'Le Van C', 'levanc@example.com', '1988-03-10', true, 2);

-- 2. Insert Hotels
INSERT INTO hotels (hotel_name, hotel_price, address, number_floor) VALUES
('Grand Palace Hotel Hanoi', 1500000, '123 Hoan Kiem District, Hanoi', 15),
('Seaside Resort Da Nang', 2000000, '456 Beach Road, Da Nang', 8),
('Mountain View Lodge Sapa', 800000, '789 Mountain Path, Sapa', 5),
('City Center Inn HCMC', 1200000, '321 Nguyen Hue Boulevard, Ho Chi Minh City', 12);

-- 3. Insert Hotel Bedrooms
-- Grand Palace Hotel rooms
INSERT INTO hotel_bedroom (room_number, price, room_type, hotel_id) VALUES
(101, 1500000, 'Deluxe King', 1),
(102, 2500000, 'Executive Suite', 1),
(201, 1000000, 'Standard Double', 1),
(202, 1500000, 'Deluxe Twin', 1);

-- Seaside Resort rooms
INSERT INTO hotel_bedroom (room_number, price, room_type, hotel_id) VALUES
(101, 2000000, 'Ocean View Suite', 2),
(102, 1400000, 'Deluxe Queen', 2),
(201, 900000, 'Standard', 2);

-- Mountain View Lodge rooms
INSERT INTO hotel_bedroom (room_number, price, room_type, hotel_id) VALUES
(1, 800000, 'Cozy Mountain Room', 3),
(2, 1100000, 'Premium Mountain View', 3);

-- City Center Inn rooms
INSERT INTO hotel_bedroom (room_number, price, room_type, hotel_id) VALUES
(501, 1300000, 'Business Class', 4),
(502, 2200000, 'Junior Suite', 4),
(601, 950000, 'Standard Twin', 4);

-- 4. Insert Flights
-- Vietnam Airlines flights
INSERT INTO flight (ticket_class, airline_name, price, check_in_date, check_out_date, number_of_chairs, seats_available, version) VALUES
('BUSINESS_CLASS', 'Vietnam Airlines', 5500000, '2026-02-01 08:00:00', '2026-02-01 10:30:00', 20, 20, 0),
('NORMAL_CLASS', 'Vietnam Airlines', 2200000, '2026-02-01 08:00:00', '2026-02-01 10:30:00', 150, 150, 0),
('BUSINESS_CLASS', 'Vietnam Airlines', 6000000, '2026-02-05 14:00:00', '2026-02-05 16:30:00', 20, 20, 0),
('NORMAL_CLASS', 'Vietnam Airlines', 2500000, '2026-02-05 14:00:00', '2026-02-05 16:30:00', 150, 150, 0),
('BUSINESS_CLASS', 'Vietnam Airlines', 5800000, '2026-02-10 06:00:00', '2026-02-10 08:30:00', 20, 20, 0),
('NORMAL_CLASS', 'Vietnam Airlines', 2300000, '2026-02-10 06:00:00', '2026-02-10 08:30:00', 150, 150, 0);

-- VietJet Air flights
INSERT INTO flight (ticket_class, airline_name, price, check_in_date, check_out_date, number_of_chairs, seats_available, version) VALUES
('BUSINESS_CLASS', 'VietJet Air', 4000000, '2026-02-02 09:00:00', '2026-02-02 11:00:00', 15, 15, 0),
('NORMAL_CLASS', 'VietJet Air', 1500000, '2026-02-02 09:00:00', '2026-02-02 11:00:00', 180, 180, 0),
('BUSINESS_CLASS', 'VietJet Air', 4200000, '2026-02-07 15:00:00', '2026-02-07 17:00:00', 15, 15, 0),
('NORMAL_CLASS', 'VietJet Air', 1600000, '2026-02-07 15:00:00', '2026-02-07 17:00:00', 180, 180, 0),
('BUSINESS_CLASS', 'VietJet Air', 3800000, '2026-02-12 07:30:00', '2026-02-12 09:30:00', 15, 15, 0),
('NORMAL_CLASS', 'VietJet Air', 1400000, '2026-02-12 07:30:00', '2026-02-12 09:30:00', 180, 180, 0);

-- Bamboo Airways flights
INSERT INTO flight (ticket_class, airline_name, price, check_in_date, check_out_date, number_of_chairs, seats_available, version) VALUES
('BUSINESS_CLASS', 'Bamboo Airways', 4800000, '2026-02-03 10:00:00', '2026-02-03 12:30:00', 18, 18, 0),
('NORMAL_CLASS', 'Bamboo Airways', 1900000, '2026-02-03 10:00:00', '2026-02-03 12:30:00', 160, 160, 0),
('BUSINESS_CLASS', 'Bamboo Airways', 5000000, '2026-02-08 16:00:00', '2026-02-08 18:30:00', 18, 18, 0),
('NORMAL_CLASS', 'Bamboo Airways', 2000000, '2026-02-08 16:00:00', '2026-02-08 18:30:00', 160, 160, 0),
('BUSINESS_CLASS', 'Bamboo Airways', 4600000, '2026-02-15 08:00:00', '2026-02-15 10:30:00', 18, 18, 0),
('NORMAL_CLASS', 'Bamboo Airways', 1800000, '2026-02-15 08:00:00', '2026-02-15 10:30:00', 160, 160, 0);

-- Pacific Airlines flights
INSERT INTO flight (ticket_class, airline_name, price, check_in_date, check_out_date, number_of_chairs, seats_available, version) VALUES
('NORMAL_CLASS', 'Pacific Airlines', 1200000, '2026-02-04 11:00:00', '2026-02-04 13:00:00', 180, 180, 0),
('NORMAL_CLASS', 'Pacific Airlines', 1300000, '2026-02-09 17:00:00', '2026-02-09 19:00:00', 180, 180, 0),
('NORMAL_CLASS', 'Pacific Airlines', 1100000, '2026-02-14 06:30:00', '2026-02-14 08:30:00', 180, 180, 0);

-- Commit all changes
COMMIT;
