/* ============================================================
   Travel Booking System (H2) - Schema + Integrity Hardening
   ------------------------------------------------------------
   Goals:
   - Keep ALL existing table/column names (backward compatible)
   - Add CHECK constraints, UNIQUE constraints, FK constraints
   - Add performance indexes aligned with JPA + reporting
   ------------------------------------------------------------
   Notes:
   - H2 supports CHECK constraints (enforced).
   - Email format check is "basic pattern" (course-friendly).
   - Use CREATE TABLE IF NOT EXISTS to survive devtools restarts.
   ============================================================ */

-- ============================================================
-- 0) Core tables
-- ============================================================

CREATE TABLE IF NOT EXISTS roles (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     role_code VARCHAR(30) NOT NULL,

    CONSTRAINT uq_roles_role_code UNIQUE (role_code),

    -- Enforce RoleCode enum
    CONSTRAINT ck_roles_role_code CHECK (role_code IN ('ADMIN', 'USER'))
    );

CREATE TABLE IF NOT EXISTS users (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     phone VARCHAR(30) NOT NULL,
    password VARCHAR(255) NOT NULL,
    full_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    birthday DATE NULL,
    status BOOLEAN NOT NULL,
    role_id BIGINT NOT NULL,

    CONSTRAINT uq_users_phone UNIQUE (phone),
    CONSTRAINT uq_users_email UNIQUE (email),

    -- Basic email validation (not perfect, but good for grading)
    CONSTRAINT ck_users_email_format CHECK (email LIKE '%_@_%._%'),

    CONSTRAINT fk_users_roles FOREIGN KEY (role_id) REFERENCES roles(id)
    );

CREATE INDEX IF NOT EXISTS idx_users_role_id ON users(role_id);

CREATE TABLE IF NOT EXISTS payment (
                                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       status VARCHAR(30) NOT NULL,

    -- Enforce PaymentStatus enum
    CONSTRAINT ck_payment_status CHECK (status IN ('PAID', 'UNPAID', 'VERIFYING', 'PAYMENT_FAILED'))
    );

CREATE INDEX IF NOT EXISTS idx_payment_status ON payment(status);

CREATE TABLE IF NOT EXISTS flight (
                                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      ticket_class VARCHAR(30) NOT NULL,
    airline_name VARCHAR(200) NOT NULL,
    price DOUBLE NOT NULL,
    check_in_date DATE NOT NULL,
    check_out_date DATE NOT NULL,
    number_of_chairs INT NOT NULL,
    seats_available INT NOT NULL,
    version BIGINT NULL,

    -- Enforce TicketClass enum
    CONSTRAINT ck_flight_ticket_class CHECK (ticket_class IN ('BUSINESS_CLASS', 'NORMAL_CLASS')),

    CONSTRAINT ck_flight_price CHECK (price > 0),
    CONSTRAINT ck_flight_date_range CHECK (check_in_date < check_out_date),
    CONSTRAINT ck_flight_seats CHECK (
                                         number_of_chairs >= 0 AND
                                         seats_available >= 0 AND
                                         seats_available <= number_of_chairs
                                     )
    );

CREATE INDEX IF NOT EXISTS idx_flight_check_in ON flight(check_in_date);
CREATE INDEX IF NOT EXISTS idx_flight_check_out ON flight(check_out_date);
CREATE INDEX IF NOT EXISTS idx_flight_ticket_class ON flight(ticket_class);
CREATE INDEX IF NOT EXISTS idx_flight_airline ON flight(airline_name);

CREATE TABLE IF NOT EXISTS hotels (
                                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      hotel_name VARCHAR(255) NOT NULL,
    hotel_price DOUBLE NOT NULL,
    address VARCHAR(500) NOT NULL,
    number_floor INT NOT NULL,

    CONSTRAINT ck_hotels_price CHECK (hotel_price > 0),
    CONSTRAINT ck_hotels_floor CHECK (number_floor >= 1)
    );

CREATE INDEX IF NOT EXISTS idx_hotels_name ON hotels(hotel_name);
CREATE INDEX IF NOT EXISTS idx_hotels_address ON hotels(address);

CREATE TABLE IF NOT EXISTS hotel_bedroom (
                                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                             room_number BIGINT NOT NULL,
                                             price DOUBLE NOT NULL,
                                             room_type VARCHAR(100) NOT NULL,
    hotel_id BIGINT NOT NULL,

    CONSTRAINT ck_hotel_bedroom_price CHECK (price > 0),
    CONSTRAINT uq_bedroom_hotel_room UNIQUE (hotel_id, room_number),
    CONSTRAINT fk_hotel_bedroom_hotels FOREIGN KEY (hotel_id) REFERENCES hotels(id)
    );

CREATE INDEX IF NOT EXISTS idx_bedroom_hotel_id ON hotel_bedroom(hotel_id);
CREATE INDEX IF NOT EXISTS idx_bedroom_room_number ON hotel_bedroom(room_number);

CREATE TABLE IF NOT EXISTS orders (
                                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      destination VARCHAR(255) NOT NULL,
    number_of_people INT NOT NULL,
    order_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    check_in_date TIMESTAMP NULL,
    check_out_date TIMESTAMP NULL,
    start_hotel TIMESTAMP NULL,
    end_hotel TIMESTAMP NULL,
    total_price DOUBLE NOT NULL DEFAULT 0,
    user_id BIGINT NULL,
    payment_id BIGINT NULL,
    flight_id BIGINT NULL,
    hotel_id BIGINT NULL,
    bedrooms VARCHAR(2000) NULL,

    CONSTRAINT ck_orders_people CHECK (number_of_people > 0),
    CONSTRAINT ck_orders_total_price CHECK (total_price >= 0),

    -- If both ends exist, start must be < end
    CONSTRAINT ck_orders_flight_date_range CHECK (
                                                     check_in_date IS NULL OR check_out_date IS NULL OR check_in_date < check_out_date
                                                 ),
    CONSTRAINT ck_orders_hotel_date_range CHECK (
                                                    start_hotel IS NULL OR end_hotel IS NULL OR start_hotel < end_hotel
                                                ),

    CONSTRAINT fk_orders_users FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_orders_payment FOREIGN KEY (payment_id) REFERENCES payment(id),
    CONSTRAINT fk_orders_flight FOREIGN KEY (flight_id) REFERENCES flight(id),
    CONSTRAINT fk_orders_hotels FOREIGN KEY (hotel_id) REFERENCES hotels(id)
    );

CREATE INDEX IF NOT EXISTS idx_orders_user_id ON orders(user_id);
CREATE INDEX IF NOT EXISTS idx_orders_payment_id ON orders(payment_id);
CREATE INDEX IF NOT EXISTS idx_orders_flight_id ON orders(flight_id);
CREATE INDEX IF NOT EXISTS idx_orders_hotel_id ON orders(hotel_id);
CREATE INDEX IF NOT EXISTS idx_orders_destination ON orders(destination);
CREATE INDEX IF NOT EXISTS idx_orders_order_date ON orders(order_date);

-- Helpful covering index for revenue reports
CREATE INDEX IF NOT EXISTS idx_orders_user_date_cover ON orders(user_id, order_date);

CREATE TABLE IF NOT EXISTS flight_seats (
                                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                            flight_id BIGINT NOT NULL,
                                            seat_number VARCHAR(10) NOT NULL,
    is_booked BOOLEAN NOT NULL DEFAULT FALSE,
    order_id BIGINT NULL,
    version BIGINT NULL,

    CONSTRAINT uq_flight_seats_flight_seat UNIQUE (flight_id, seat_number),

    -- Booking consistency:
    -- booked => order_id not null, free => order_id null
    CONSTRAINT ck_flight_seats_booking_consistency CHECK (
(is_booked = TRUE  AND order_id IS NOT NULL) OR
(is_booked = FALSE AND order_id IS NULL)
    ),

    CONSTRAINT fk_flight_seats_flight FOREIGN KEY (flight_id) REFERENCES flight(id),
    CONSTRAINT fk_flight_seats_orders FOREIGN KEY (order_id) REFERENCES orders(id)
    );

CREATE INDEX IF NOT EXISTS idx_flight_seat_flight_id ON flight_seats(flight_id);
CREATE INDEX IF NOT EXISTS idx_flight_seat_order_id ON flight_seats(order_id);
CREATE INDEX IF NOT EXISTS idx_flight_seat_is_booked ON flight_seats(flight_id, is_booked);

CREATE TABLE IF NOT EXISTS hotel_booking (
                                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                             order_id BIGINT NOT NULL,
                                             hotel_id BIGINT NOT NULL,
                                             hotel_bedroom_id BIGINT NOT NULL,
                                             start_date DATE NOT NULL,
                                             end_date DATE NOT NULL,

                                             CONSTRAINT ck_hotel_booking_date_range CHECK (start_date < end_date),

    CONSTRAINT fk_hotel_booking_orders FOREIGN KEY (order_id) REFERENCES orders(id),
    CONSTRAINT fk_hotel_booking_hotels FOREIGN KEY (hotel_id) REFERENCES hotels(id),
    CONSTRAINT fk_hotel_booking_hotel_bedroom FOREIGN KEY (hotel_bedroom_id) REFERENCES hotel_bedroom(id)
    );

CREATE INDEX IF NOT EXISTS idx_hb_order_id ON hotel_booking(order_id);
CREATE INDEX IF NOT EXISTS idx_hb_hotel_bedroom_dates ON hotel_booking(hotel_id, hotel_bedroom_id, start_date, end_date);

CREATE TABLE IF NOT EXISTS reviews (
                                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       rating INT NOT NULL,
                                       comment VARCHAR(1000) NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    user_id BIGINT NOT NULL,
    hotel_id BIGINT NOT NULL,
    order_id BIGINT NOT NULL,

    CONSTRAINT ck_reviews_rating CHECK (rating BETWEEN 1 AND 5),
    CONSTRAINT uq_reviews_order_id UNIQUE (order_id),

    CONSTRAINT fk_reviews_users FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_reviews_hotels FOREIGN KEY (hotel_id) REFERENCES hotels(id),
    CONSTRAINT fk_reviews_orders FOREIGN KEY (order_id) REFERENCES orders(id)
    );

CREATE INDEX IF NOT EXISTS idx_reviews_hotel_id ON reviews(hotel_id);
CREATE INDEX IF NOT EXISTS idx_reviews_user_id ON reviews(user_id);
CREATE INDEX IF NOT EXISTS idx_reviews_order_id ON reviews(order_id);
CREATE INDEX IF NOT EXISTS idx_reviews_created_at ON reviews(created_at);

CREATE TABLE IF NOT EXISTS contacts (
                                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        full_name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    subject VARCHAR(200) NOT NULL,
    message VARCHAR(2000) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,

    CONSTRAINT ck_contacts_email_format CHECK (email LIKE '%_@_%._%')
    );

CREATE INDEX IF NOT EXISTS idx_contact_email ON contacts(email);
CREATE INDEX IF NOT EXISTS idx_contact_created_at ON contacts(created_at);
CREATE INDEX IF NOT EXISTS idx_contact_is_read ON contacts(is_read);

CREATE TABLE IF NOT EXISTS password_reset_tokens (
                                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                     token VARCHAR(255) NOT NULL,
    user_id BIGINT NOT NULL,
    expiry_date TIMESTAMP NOT NULL,
    used BOOLEAN NOT NULL DEFAULT FALSE,

    CONSTRAINT uq_password_reset_tokens_token UNIQUE (token),
    CONSTRAINT fk_password_reset_tokens_users FOREIGN KEY (user_id) REFERENCES users(id)
    );

CREATE INDEX IF NOT EXISTS idx_token ON password_reset_tokens(token);
CREATE INDEX IF NOT EXISTS idx_token_user_id ON password_reset_tokens(user_id);

-- ============================================================
-- 1) Audit table (new, does not break app logic)
-- ============================================================

CREATE TABLE IF NOT EXISTS audit_log (
                                         audit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                         changed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                         changed_by VARCHAR(100) NULL,
    table_name VARCHAR(100) NOT NULL,
    operation VARCHAR(10) NOT NULL,      -- INSERT / UPDATE / DELETE
    primary_key VARCHAR(200) NULL,       -- e.g. "id=123"
    old_data CLOB NULL,
    new_data CLOB NULL
    );
